/// Flutter icons FitQaIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FitQaIcon
///      fonts:
///       - asset: fonts/FitQaIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FitQaIcon {
  FitQaIcon._();

  static const _kFontFam = 'FitQaIcon';
  static const String? _kFontPkg = null;

  static const IconData my_page = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop_down = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData modification = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_enter = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enter = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trainer = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
