// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDurbYv7HNqW4fKJqceFbzP3BAEUk3M9po',
    appId: '1:980187310835:web:c70f006f297a6f39942586',
    messagingSenderId: '980187310835',
    projectId: 'fitqa-6b0d2',
    authDomain: 'fitqa-6b0d2.firebaseapp.com',
    storageBucket: 'fitqa-6b0d2.appspot.com',
    measurementId: 'G-47M6G3M7MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXDfSnjgWYmtn5HgO1VC8Xt4Wg1c0QAWc',
    appId: '1:980187310835:android:a573042968249012942586',
    messagingSenderId: '980187310835',
    projectId: 'fitqa-6b0d2',
    storageBucket: 'fitqa-6b0d2.appspot.com',
  );
}
